## YAML Tlanguage: node_js
node_js:
  - "0.10"
before_script:
  - npm install bower
  - ./node_modules/bower/bin/bower install
  - npm install
script:
  - "npm test"
after_success:
  - node_modules/grunt-cli/bin/grunt coverage